version: "3"
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: host.docker.internal
      DB_NAME: taskmanager
      DB_USER: postgres
      DB_PASS: password
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
